### ISSUE TITLE
Can this tool be used to take incremental backup

### ISSUE THREAD

**Issue by hakimkartik** [helpshift/scyllabackup#3]
Say i have cluster on day 1 having 2 keyspaces , having a combined size of 100G, using the tool i triggered the backup and uploaded 100G of data to s3 by the end of day.
On day 2 say my cluster receives new data and so the total size of the cluster become about 200G(100G of new data).
So when i trigger the backup for day 2
will the tool start uploading data from the beginning (i.e. all of 200G) 
or will only upload the new data(100G)

**Comment by perfectayush** [comment]
Duplicate of #2
