### ISSUE TITLE
Using AWS IAM roles instead of access keys

### ISSUE THREAD

**Issue by kannan-zeotap** [helpshift/scyllabackup#5]
Hi,

Is there any way we can use IAM roles for backup to S3 instead of access key and secret access key? Scyllabackup command says both access key and secret access key are mandatory.
--s3-aws-key AWS_KEY  Mandatory if provider is s3 (default: None)
  --s3-aws-secret AWS_SECRET
                        Mandatory if provider is s3 (default: None)
Sharing secret key in plaintext is not encouraged, so wondering can we use IAM role attached to the instance to take backup.

**Comment by perfectayush** [comment]
I am referring documentation here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials

Looks like the keys and secret can be fetched via a simple curl. You can wrap scyllabackup in a shell script to fetch temp creds via curl and store it in variable and pass them to a call in scyllabackup. And use that shell script as your interface to scyllabackup

I don't see a point of implementing such a complicated interface directly in the scyllabackup.

**Comment by perfectayush** [comment]
@kannan-zeotap I also noticed, you will require to pass the session token, which is currently not support by cli parameters passed. However, the underlying storage library is using boto3 and I can read here: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html that session token can be passed as environment variable. It should work if you just setup the ENV var for session token in your shell script for scyllabackup.
